[package]
name = "nerqia"
version = "1.0.0"
description = "Nerqia Commerce OS desktop and mobile client"
authors = ["Nerqia"]
license = "UNLICENSED"
repository = "https://github.com/santyperez145/Gestiona"
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nerqia_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1" }
tauri-plugin-deep-link = "2.6.1"
tauri-plugin-log = "2.8.0"
tauri-plugin-opener = "2.7.0"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = { version = "2.5.2", features = ["deep-link"] }
